#!/bin/bash

SMOOTH_DIST=5
MAX_POINTS=1900

OUTDIR=build

files=json/*.json

mkdir -p $OUTDIR

for f in $files; do
    name=$(basename "$f" .json)

    printf -- "-------------------------------------------------------\n"
    printf "Building %s\n" "$name"
    printf -- "-------------------------------------------------------\n"

    gpx_name=${OUTDIR}/${name}.gpx
    track_name="$name"

    case "$name" in
        Oregon_North_Cascades_Route) track_name="ONCR" ;;
        Oregon_Newberry_Summer_Route) track_name="ONSR" ;;
        Oregon_Santiam_Crossing_Route) track_name="OSCR" ;;
        Unofficial_OBCDR2) track_name="OBCDR2" ;;
        Unofficial_OBCDR3) track_name="OBCDR3" ;;
        Unofficial_OBCDR4) track_name="OBCDR4" ;;
        Unofficial_OBCDR5) track_name="OBCDR5" ;;
        Unofficial_OBCDR6) track_name="OBCDR6" ;;
        California_Trans-Sierra_Route) track_name="CTSR" ;;
        California_Ponderosa_Way_Route) track_name="CPWR" ;;
    esac

    ./gjretrack.py -e $SMOOTH_DIST -m 1900 -j -v "$f" | ./gjtogpx.py - "$track_name" > "$gpx_name"
done
